version: "2.4"


services:
  postgres:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    container_name: news_portal
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/project

    command: bash entrypoint.sh

volumes:
  pg_data:
