# Generated by Django 4.2.6 on 2023-12-26 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('link', models.CharField(max_length=350, verbose_name='Посилання')),
            ],
            options={
                'verbose_name': 'Артикль',
                'verbose_name_plural': 'Артиклі',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Імя')),
                ('description', models.CharField(blank=True, max_length=1500, verbose_name='Опис')),
                ('route', models.URLField(blank=True, max_length=400, verbose_name='Посилання')),
                ('facebook', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фейсбук')),
                ('twitter', models.CharField(blank=True, max_length=50, null=True, verbose_name='Твіттер')),
                ('telegram', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телеграм')),
                ('articles', models.ManyToManyField(to='news.articles')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Автори',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='NewsUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('profile_image', models.CharField(blank=True, max_length=500, null=True, verbose_name='Картинка профиля')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='Емейл')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_sum', models.IntegerField()),
                ('rating_count', models.IntegerField()),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='TranslationKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=2000, null=True, verbose_name='Ключ')),
                ('requests', models.IntegerField(default=0, verbose_name='Використано запросів')),
                ('active', models.BooleanField(default=False, verbose_name='Ключ який використовується зараз')),
            ],
            options={
                'verbose_name': 'Ключ для перекладу',
                'verbose_name_plural': 'Ключі для перекладу',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, null=True, verbose_name='Назва')),
                ('news_creator', models.CharField(blank=True, max_length=300, null=True, verbose_name='Власник(и) новини')),
                ('link', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Посилання')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Посилання на картинку')),
                ('description', models.TextField(blank=True, max_length=800, null=True, verbose_name='Опис')),
                ('pub_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата публікації')),
                ('update_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата оновлення')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Країна')),
                ('content', models.TextField(max_length=7000, null=True, verbose_name='Контент')),
                ('custom_url', models.CharField(default=None, max_length=50, null=True, unique=True, verbose_name='Кастомне посилання')),
                ('time_to_read', models.IntegerField(blank=True, null=True, verbose_name='Час прочитання')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('img_alt', models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Альтернативна назва картинки')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Підтвердження валідності новини для її виставлення')),
                ('translated', models.BooleanField(default=False, editable=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.author')),
                ('categories', models.ManyToManyField(blank=True, to='news.categories')),
                ('tags', models.ManyToManyField(blank=True, to='news.tags')),
            ],
            options={
                'verbose_name': 'Новина',
                'verbose_name_plural': 'Новини',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.newsuser')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.news')),
            ],
        ),
    ]
