# Generated by Django 4.2.6 on 2024-01-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsuser',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Емейл'),
        ),
    ]
