# Generated by Django 4.2.6 on 2024-01-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_author_news_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsuser',
            name='saved_news',
            field=models.ManyToManyField(null=True, related_name='saved_news', to='news.news'),
        ),
    ]
