# Generated by Django 4.2.6 on 2024-01-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_author_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='rating',
        ),
        migrations.AddField(
            model_name='news',
            name='rating',
            field=models.ManyToManyField(blank=True, to='news.rating'),
        ),
    ]
