# Generated by Django 4.2.6 on 2024-01-26 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_savednews_news_custom_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsuser',
            name='savednews',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='news.newsuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savednews',
            name='news',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='news.news'),
        ),
    ]
