# Generated by Django 4.2.6 on 2024-01-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsuser_saved_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='rating',
        ),
        migrations.AddField(
            model_name='news',
            name='rating',
            field=models.ManyToManyField(null=True, to='news.rating'),
        ),
    ]
