# Generated by Django 4.2.6 on 2023-10-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_content_alter_news_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(default='Site Admin', max_length=50, null=True),
        ),
    ]
