# Generated by Django 4.2.6 on 2024-01-04 22:00

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_news_rating_news_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='news_id',
        ),
        migrations.AlterField(
            model_name='rating',
            name='user_email',
            field=models.CharField(max_length=100, unique=True, verbose_name=news.models.NewsUser),
        ),
    ]
