# Generated by Django 4.2.6 on 2024-01-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_rating_news_id_alter_rating_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='news_id',
            field=models.IntegerField(null=True, verbose_name='Айди новости'),
        ),
        migrations.RemoveField(
            model_name='news',
            name='rating',
        ),
        migrations.AlterField(
            model_name='rating',
            name='user_email',
            field=models.CharField(max_length=100, unique=True, verbose_name='Емейл'),
        ),
        migrations.AddField(
            model_name='news',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
