# Generated by Django 4.2.6 on 2024-01-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_news_rating_news_rating'),
    ]

    operations = [
    #     migrations.RemoveField(
    #         model_name='rating',
    #         name='news_id',
    #     ),
    #     migrations.AlterField(
    #         model_name='news',
    #         name='rating',
    #         field=models.ManyToManyField(related_name='news_rating', to='news.rating'),
    #     ),
    #     migrations.AlterField(
    #         model_name='newsuser',
    #         name='saved_news',
    #         field=models.ManyToManyField(related_name='saved_news', to='news.news'),
    #     ),
    ]
