# Generated by Django 4.2.6 on 2024-01-26 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_savednews_news_custom_url_newsuser_savednews_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsuser',
            name='savednews',
        ),
        migrations.AddField(
            model_name='savednews',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='news.newsuser'),
            preserve_default=False,
        ),
    ]
