# Generated by Django 4.2.6 on 2023-10-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_author_alter_news_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News'},
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(default='SimpleITNews', max_length=50),
        ),
    ]
