# Generated by Django 4.2.6 on 2024-01-26 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_newsuser_savednews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savednews',
            name='news',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='news.news', unique=True),
        ),
    ]
