# Generated by Django 4.2.6 on 2024-01-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_rating_news_id_alter_news_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_custom_url', models.CharField(default=None, max_length=50, null=True, unique=True, verbose_name='Кастомне посилання')),
            ],
        ),
        migrations.AlterField(
            model_name='newsuser',
            name='saved_news',
            field=models.ManyToManyField(related_name='saved_news', to='news.savednews'),
        ),
    ]
