# Generated by Django 4.2.6 on 2024-01-26 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_savednews_news_custom_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savednews',
            name='news_custom_url',
        ),
    ]
