# Generated by Django 4.2.6 on 2024-01-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_savednews_alter_newsuser_saved_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savednews',
            name='news_custom_url',
            field=models.CharField(null=True, verbose_name='Кастомне посилання'),
        ),
    ]
