# Generated by Django 4.2.6 on 2024-01-05 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_author_news_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='articles',
        ),
    ]
