# Generated by Django 4.2.6 on 2024-01-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_savednews_news_custom_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsuser',
            name='saved_news',
            field=models.ManyToManyField(related_name='saved_news', to='news.news'),
        ),
    ]
