# Generated by Django 4.2.6 on 2023-11-13 17:42

from django.db import migrations, models

   
def migrate_old_data(apps, schema_editor):
    News = apps.get_model('news', 'news')
    i = 0
    for news in News.objects.all():
        news.custom_url = f'Null_{i}'
        news.save(update_fields=["custom_url"])
        i += 1

class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_news_content_alter_news_title'),
    ]

    operations = [
        migrations.RunPython(migrate_old_data, reverse_code=migrations.RunPython.noop),

        migrations.AddField(
            model_name='news',
            name='custom_url',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),

    ]
