# Generated by Django 4.2.6 on 2023-11-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_news_content_alter_news_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='custom_url',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
