# Generated by Django 4.2.6 on 2023-11-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_news_custom_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='custom_url',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
