# Generated by Django 4.2.6 on 2024-01-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_newsuser_saved_news'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='news',
        #     name='rating',
        #     field=models.ManyToManyField(blank=True, related_name='news_rating', to='news.rating'),
        # ),
    ]
