# Generated by Django 4.2.6 on 2024-02-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_newsuser_google_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsuser',
            name='google_id',
            field=models.CharField(default='1'),
        ),
    ]
