# Generated by Django 4.2.6 on 2024-01-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_news_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsuser',
            name='saved_news',
            field=models.ManyToManyField(related_name='saved_news', to='news.savednews'),
        ),
    ]
