# Generated by Django 4.2.6 on 2023-11-18 18:57

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_rename_isaproved_news_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        
    ]
