# Generated by Django 4.2.6 on 2023-11-18 19:07

from django.db import migrations, models

def migrate_old_data(apps, schema_editor):
    News = apps.get_model('news', 'news')
    for news in News.objects.all():
        if news.content:
            news.content = news.content[0:1800]
            news.save(update_fields=["content"])

class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_news_description_alter_news_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RunPython(migrate_old_data, reverse_code=migrations.RunPython.noop),
    ]
