# Generated by Django 4.2.6 on 2024-01-19 14:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [       
        migrations.CreateModel(
            name='NewsUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('profile_image', models.CharField(blank=True, max_length=500, null=True, verbose_name='Картинка профиля')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='Емейл')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]