# Generated by Django 4.2.6 on 2024-01-06 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_newsuser_saved_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsuser',
            name='saved_news',
        ),
        migrations.AddField(
            model_name='savednews',
            name='newsuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newsuser'),
        ),
    ]
