# Generated by Django 4.2.6 on 2024-01-06 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_remove_newsuser_saved_news_savednews_newsuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savednews',
            name='newsuser',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='news.newsuser'),
        ),
    ]
