# Generated by Django 4.2.6 on 2024-01-09 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_savednews_newsuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='rating',
            new_name='news_rating',
        ),
    ]
