# Generated by Django 4.2.6 on 2024-01-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_rename_rating_news_news_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_rating',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='news_id',
        ),
    ]
