# Generated by Django 4.2.6 on 2024-01-10 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_remove_news_news_rating_remove_rating_news_id'),
    ]

    operations = [
        #migrations.DeleteModel(
        #    name='Rating',
        #),
    ]
