# Generated by Django 4.2.6 on 2023-11-18 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_alter_news_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='surname',
        ),
    ]
