# Generated by Django 4.2.6 on 2023-11-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_remove_author_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_creator',
            field=models.CharField(default='SimpleITNews', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='articles',
            field=models.ManyToManyField(to='news.articles'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ManyToManyField(to='news.author'),
        ),
    ]
