# Generated by Django 4.2.6 on 2024-01-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='users', to='news.newsuser'),
        ),
    ]
