# Generated by Django 4.2.6 on 2024-01-10 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_news_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='likes',
        ),
    ]
