# Generated by Django 4.2.6 on 2023-11-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_news_news_creator_alter_author_articles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='link',
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(to='news.tags'),
        ),
        migrations.AddField(
            model_name='tags',
            name='tags_filter',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
