# Generated by Django 4.2.6 on 2023-11-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_remove_articles_link_news_tags_tags_tags_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='tags_filter',
        ),
        migrations.AlterField(
            model_name='tags',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
