# Generated by Django 4.2.6 on 2024-01-10 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_rating_news_rates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='story',
            new_name='news',
        ),
    ]
