# Generated by Django 4.2.6 on 2023-11-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_alter_news_content_alter_news_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='custom_url',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
