# Generated by Django 4.2.6 on 2023-11-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_alter_news_content_alter_news_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='route',
            field=models.URLField(blank=True, max_length=400),
        ),
    ]
