# Generated by Django 4.2.6 on 2024-01-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_rename_story_rating_news'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('news', 'user')},
        ),
    ]
