# Generated by Django 4.2.6 on 2023-11-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_alter_news_custom_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='custom_url',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
