# Generated by Django 4.2.6 on 2024-01-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_alter_rating_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='rates',
        ),
        migrations.AddField(
            model_name='news',
            name='ratings',
            field=models.ManyToManyField(related_name='rated_news', through='news.Rating', to='news.newsuser'),
        ),
    ]
