# Generated by Django 4.2.6 on 2023-11-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_alter_author_facebook_alter_author_telegram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_creator',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
