# Generated by Django 4.2.6 on 2023-11-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_alter_news_news_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='link',
            field=models.CharField(default=123, max_length=350),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='custom_url',
            field=models.CharField(default=None, max_length=50, null=True, unique=True),
        ),
    ]
