# Generated by Django 4.2.6 on 2023-11-27 01:27

from django.db import migrations, models

def migrate_old_data(apps, schema_editor):
    News = apps.get_model('news', 'news')
    for news in News.objects.all():
        if news.news_creator:
            news.news_creator = ''
            news.save(update_fields=["news_creator"])

class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_categories_news_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_creator',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.RunPython(migrate_old_data, reverse_code=migrations.RunPython.noop),
    ]
