# Generated by Django 4.2.6 on 2023-12-01 23:26

from django.db import migrations, models

def text_to_time(text):
    word_count = 0
    for word in text:
        if word != ' ':
            word_count += 1
    
    return int(word_count/238)

def migrate_old_data(apps, schema_editor):
    News = apps.get_model('news', 'news')
    for news in News.objects.all():
        news.time_to_read = text_to_time(news.content)
        news.save(update_fields=["time_to_read"])

class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_alter_news_news_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Артикль', 'verbose_name_plural': 'Артиклі'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Автори'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новина', 'verbose_name_plural': 'Новини'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AddField(
            model_name='news',
            name='time_to_read',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='categories',
            field=models.ManyToManyField(to='news.categories'),
        ),
        migrations.RunPython(migrate_old_data, reverse_code=migrations.RunPython.noop),

    ]
