# Generated by Django 4.2.6 on 2023-12-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0028_alter_news_content_alter_news_time_to_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='rating',
            field=models.FloatField(default=5),
        ),
    ]
