# Generated by Django 4.2.6 on 2023-12-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0031_news_img_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img_alt',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
