# Generated by Django 4.2.6 on 2023-12-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0032_alter_news_img_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='link',
            field=models.CharField(max_length=350, verbose_name='Посилання'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.CharField(blank=True, max_length=1500, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='author',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Фейсбук'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Імя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='route',
            field=models.URLField(blank=True, max_length=400, verbose_name='Посилання'),
        ),
        migrations.AlterField(
            model_name='author',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Телеграм'),
        ),
        migrations.AlterField(
            model_name='author',
            name='twitter',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Твіттер'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(max_length=7000, null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='news',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Країна'),
        ),
        migrations.AlterField(
            model_name='news',
            name='custom_url',
            field=models.CharField(default=None, max_length=50, null=True, unique=True, verbose_name='Кастомне посилання'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, max_length=800, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Посилання на картинку'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img_alt',
            field=models.CharField(default=None, max_length=300, null=True, verbose_name='Альтернативна назва картинки'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Підтвердження валідності новини для її виставлення'),
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Посилання'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_creator',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Власник(и) новини'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата публікації'),
        ),
        migrations.AlterField(
            model_name='news',
            name='rating',
            field=models.FloatField(default=5, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='news',
            name='time_to_read',
            field=models.IntegerField(null=True, verbose_name='Час прочитання'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=150, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='news',
            name='update_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата оновлення'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
    ]
