# Generated by Django 3.2.6 on 2023-12-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0034_news_translated'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=2000, null=True, verbose_name='Ключ')),
                ('requests', models.IntegerField(default=0, editable=False, verbose_name='Використано запросів')),
            ],
        ),
    ]
