# Generated by Django 4.2.6 on 2023-12-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0035_translationkeys'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translationkeys',
            options={'verbose_name': 'Ключ для перекладу', 'verbose_name_plural': 'Ключі для перекладу'},
        ),
        migrations.AlterField(
            model_name='news',
            name='categories',
            field=models.ManyToManyField(blank=True, to='news.categories'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img_alt',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Альтернативна назва картинки'),
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Посилання'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, to='news.tags'),
        ),
        migrations.AlterField(
            model_name='news',
            name='time_to_read',
            field=models.IntegerField(blank=True, null=True, verbose_name='Час прочитання'),
        ),
        migrations.AlterField(
            model_name='news',
            name='translated',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
