# Generated by Django 4.2.6 on 2023-12-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0036_alter_translationkeys_options_alter_news_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationkeys',
            name='requests',
            field=models.IntegerField(default=0, verbose_name='Використано запросів'),
        ),
    ]
