# Generated by Django 4.2.6 on 2023-12-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0037_alter_translationkeys_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationkeys',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Ключ який використовується зараз'),
        ),
    ]
