# Generated by Django 4.2.6 on 2023-12-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0038_translationkeys_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, null=True, verbose_name='Фамилия')),
                ('profile_image', models.CharField(max_length=500, null=True, verbose_name='Картинка профиля')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='Емейл')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
