# Generated by Django 4.2.6 on 2023-12-25 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0042_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_sum', models.IntegerField()),
                ('rating_count', models.IntegerField()),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
            ],
        ),
    ]
