# Generated by Django 4.2.6 on 2023-12-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0043_rating_alter_newsuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsuser',
            name='email',
            field=models.CharField(max_length=100, unique=True, verbose_name='Емейл'),
        ),
    ]
