# Generated by Django 4.2.6 on 2023-12-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0044_rating_alter_news_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='user_email',
            field=models.CharField(default=None, max_length=100, unique=True, verbose_name='Емейл'),
        ),
    ]
