# Generated by Django 4.2.6 on 2023-12-25 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0044_alter_newsuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.rating'),
        ),
    ]
