# Generated by Django 4.2.6 on 2023-12-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0045_alter_news_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rating_count',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rating_sum',
        ),
        migrations.AddField(
            model_name='rating',
            name='news_id',
            field=models.IntegerField(null=True, verbose_name='Айди новости'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user_email',
            field=models.CharField(default=2, max_length=100, unique=True, verbose_name='Емейл'),
            preserve_default=False,
        ),
    ]
