# Generated by Django 4.2.6 on 2023-12-25 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0045_rating_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='ratings_count',
            new_name='rating_count',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user_email',
        ),
        migrations.AlterField(
            model_name='news',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.rating'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_sum',
            field=models.IntegerField(),
        ),
    ]
