# Generated by Django 4.2.6 on 2023-12-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0046_remove_rating_rating_count_remove_rating_rating_sum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
